#+TITLE: ii-V Snippets
#+AUTHOR: Bartev
#+OPTIONS: num:nil toc:nil

#+LATEX_HEADER: \usepackage[cm]{fullpage}
#+LATEX_HEADER: \usepackage[headheight=15pt, headsep=10pt, top=1in, bottom=1in, left=0.75in, right=0.75in]{geometry} % Ensure sufficient header space

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhf{}
#+LATEX_HEADER: \fancyhead[L]{\textbf{ii-V-I Snippets}} % Left header with title
#+LATEX_HEADER: \fancyhead[R]{\textbf{Bartev - Lesson 26 (2024-12)}} % Right header with author
#+LATEX_HEADER: \fancyfoot[C]{\thepage}
#+LATEX_HEADER: \fancyfoot[R]{Printed \today} % Right footer with today's date
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0.4pt} % Optional: Add a horizontal rule below the header

#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \let\ps@plain\ps@fancy % Apply "fancy" style to the first page
#+LATEX_HEADER: \let\maketitle\relax % Suppress default title/author rendering
#+LATEX_HEADER: \makeatother

#+PROPERTY: header-args:lilypond :noweb yes :exports results
#+PROPERTY: header-args:lilypond :prologue (org-babel-ref-resolve "settings[]")

#+name: settings
#+begin_src lilypond :exports none
  \version "2.24.2"

  \include "lilypond-book-preamble.ly"

  \include "jazzchords.ily"
  %% \include "lilyjazz.ily"
  \include "jazzextras.ily"
  \include "roman_numeral_analysis_tool.ily"
  \include "bv_definitions.ily"

  #(ly:set-option 'use-paper-size-for-page #f)
  #(ly:set-option 'tall-page-formats 'pdf)

  #(set-global-staff-size 16)

  \paper{
    line-width=7\in
    indent=0\mm
    left-margin = 0\mm
    right-margin = 0\mm

    oddFooterMarkup=##f
    oddHeaderMarkup=##f
    bookTitleMarkup=##f
    scoreTitleMarkup=##f
    ragged-right = ##f

    #(define fonts
      (set-global-fonts
       #:music "lilyjazz"
       #:brace "lilyjazz"
       #:sans "lilyjazz-chord"
       #:factor (/ staff-height pt 18)
     ))
  }

  \layout {
    \omit Staff.TimeSignature
    \context {
      \Score
      \override SpacingSpanner.uniform-stretching = ##t
    }
  }

  global = {
    \numericTimeSignature
    \time 4/4
    %% \tempo 4=224  % this would be over the clef on the first line

    %% See here for using colors
    %% http://lilypond.org/doc/v2.19/Documentation/notation/inside-the-staff#coloring-objects
    %% \override Score.RehearsalMark.color = #(x11-color "SlateBlue2")  % example using x11 colors
    \override Score.RehearsalMark.color = #darkred
    %% http://lilypond.org/doc/v2.19/Documentation/internals/rehearsalmark
    \override Score.RehearsalMark.font-size = 6

    \set Score.rehearsalMarkFormatter = #format-mark-box-alphabet
  }

#+end_src

* Various chord changes

** Major ii-V-I
#+begin_src lilypond :file major_ii_v_i.pdf
  \score {
    \new StaffGroup <<
      \new ChordNames { \chordmode { d:m7 g:7 c:maj7 c:maj7 }}
      \new Staff {
        \global
        \key c \major
        \relative c' {
          d4 f a c
          g4 b d f
          c4 e g b
          s1
        }
      }
    >>
  }

#+end_src
** Minor ii-V-I

#+begin_src lilypond :file minor_ii_v_i.pdf
  \score {
    \new StaffGroup <<
      \new ChordNames { \chordmode { d:m7.5- g:7.9- c:m7 c:m7 }}
      \new Staff {
        \global
        \key c \major
        \relative c' {
          d4 f aes c
          g8 b d f aes r4.
          c,4 ees g bes
          s1
        }
      }
    >>
  }
#+end_src

For the half-dim chord, try the Locrian or Locrian nat 2 scales.

#+begin_src lilypond :file locrian.pdf
  c_locrian = \relative c' { c8_\markup { Locrian } des ees f ges aes bes c }
  c_locrian_nat_two = \relative c' { c8_\markup { Locrian nat 2 } d ees f ges aes bes c }

  \score {
    \new StaffGroup <<
      \new ChordNames { \chordmode { d:m7.5- }}
      \new Staff {
        \global
        \key d \major
        \relative d' {
          \transpose c d \c_locrian
          \transpose c d \c_locrian_nat_two
        }
      }
    >>
  }
#+end_src

For the G7\flat 9, try the Phrygian Dominant or altered scales.

#+begin_src lilypond :file phryg_dom.pdf
  c_phrygian_dominant = \relative c' { c8_\markup { Phrygian Dominant } des e f g aes bes c }
  c_alt_dim_whole = \relative c' { c8_\markup { Altered Scale - Diminished Whole Tone} des ees e fis gis bes c }

  \score {
    \new StaffGroup <<
      \new ChordNames { \chordmode { g:7.9- }}
      \new Staff {
        \global
        \key g \major
        \relative c' {
          \transpose c g \c_phrygian_dominant
          \transpose c g \c_alt_dim_whole
        }
      }
    >>
  }
  #+end_src
* Basic ii-V-I phrases
** In E-flat

Pellentesque dapibus suscipit ligula.  Donec posuere augue in quam.  Etiam vel tortor sodales tellus ultricies commodo.  Suspendisse potenti.  Aenean in sem ac leo mollis blandit.  Donec neque quam, dignissim in, mollis nec, sagittis eu, wisi.  Phasellus lacus.  Etiam laoreet quam sed arcu.  Phasellus at dui in ligula mollis ultricies.  Integer placerat tristique nisl.  Praesent augue.  Fusce commodo.  Vestibulum convallis, lorem a tempus semper, dui dui euismod elit, vitae placerat urna tortor vitae lacus.  Nullam libero mauris, consequat quis, varius et, dictum id, arcu.  Mauris mollis tincidunt felis.  Aliquam feugiat tellus ut neque.  Nulla facilisis, risus a rhoncus fermentum, tellus tellus lacinia purus, et dictum nunc justo sit amet elit.


#+begin_src lilypond :file e-flat.pdf
  \score {
    \new StaffGroup <<
      \new ChordNames { \chordmode { f1:m7 bes:7 ees:maj7 ees:maj7 }}
      \new Staff {
        \global
        \key ees \major
        \relative c''' {
          c8 ees d c bes aes f aes~
          aes8 f ees d ees4 f8 d~
          d8 ees f aes~ aes g f g~
          g4 r4 r2
        }
      }
      \lyrics {
        \markup \scaleDegree { 5 }2
        \markup \scaleDegree { 4 }4.
        \markup \scaleDegree { f3 }8

        \markup \scaleDegree { f7 }2
        \markup \scaleDegree { 4 }4.
        \markup \scaleDegree { 3 }8

        \markup \scaleDegree { 7 }2
        \markup \scaleDegree { 4 }4.
        \markup \scaleDegree { 3 }8

        \markup \scaleDegree { 3 }1
      }
    >>
  }
#+end_src
** G maj
#+begin_src lilypond :file g_maj.pdf
  \score {
    \new StaffGroup <<
      \new ChordNames { \chordmode { s4 a1:m7 d:7 g:maj7 g:maj7 }}
      \new Staff {
        \global
        \key g \major
        \relative c'' {
          \partial 4 { r8 g}
          \tuplet 3/2 { a8 c e } g8 fis8~ fis e~ e4~
          e8 d e fis d r r a
          aes g fis g b fis'~ fis e
          d b r2.
        }
      }
      \lyrics {
        \markup \scaleDegree {  }4
        \markup \scaleDegree { 1 }4
        \markup \scaleDegree { f7 }4.
        \markup \scaleDegree { 5 }4.
        \markup \scaleDegree {  }8

        \markup \scaleDegree { 1 }4
        \markup \scaleDegree { 3 }8
        \markup \scaleDegree { 1 }4.
        \markup \scaleDegree { 2 }8

        \markup \scaleDegree { f2 }8
        \markup \scaleDegree { 1 }8
        \markup \scaleDegree { 7 }8
        \markup \scaleDegree { 1 }8

        \markup \scaleDegree { 3 }8
        \markup \scaleDegree { 7 }4
        \markup \scaleDegree { 5 }8

        \markup \scaleDegree { 5 }8
        \markup \scaleDegree { 3 }8

      }
    >>
  }
#+end_src

** G maj (variation 2)
#+begin_src lilypond :file g_maj_v2.pdf
  \score {
    \new StaffGroup <<
      \new ChordNames { \chordmode { s4 a1:m7 d:7 g:maj7 g:maj7 }}
      \new Staff {
        \global
        \key g \major
        \relative c''' {
          a4. g8 a4. g8
          fis4. e8 fis4. e8
          d4. b8 d b a b~
          b2 r2
        }
      }
    >>
  }
#+end_src
