#+TITLE: Sax Lesson 27
#+AUTHOR: Bartev
#+OPTIONS: num:t toc:t

#+LATEX_HEADER: \usepackage[cm]{fullpage}
#+LATEX_HEADER: \usepackage[headheight=15pt, headsep=10pt, top=1in, bottom=1in, left=0.75in, right=0.75in]{geometry} % Ensure sufficient header space
#+BIND: org-latex-image-default-width ".98\\linewidth"

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhf{}
#+LATEX_HEADER: \fancyhead[L]{\textbf{ii-V-I Snippets}} % Left header with title
#+LATEX_HEADER: \fancyhead[R]{\textbf{Bartev - Lesson 27 (2025-03)}} % Right header with author
#+LATEX_HEADER: \fancyfoot[C]{\thepage}
#+LATEX_HEADER: \fancyfoot[R]{Printed \today} % Right footer with today's date
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0.4pt} % Optional: Add a horizontal rule below the header

#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \let\ps@plain\ps@fancy % Apply "fancy" style to the first page
#+LATEX_HEADER: \let\maketitle\relax % Suppress default title/author rendering
#+LATEX_HEADER: \makeatother

#+PROPERTY: header-args:lilypond :noweb yes :exports results
#+PROPERTY: header-args:lilypond :prologue (org-babel-ref-resolve "settings[]")

#+name: settings
#+begin_src lilypond :exports none
  \version "2.24.2"

  \include "lilypond-book-preamble.ly"

  \include "jazzchords.ily"
  %% \include "lilyjazz.ily"
  \include "jazzextras.ily"
  \include "roman_numeral_analysis_tool.ily"
  \include "bv_definitions.ily"

  #(ly:set-option 'use-paper-size-for-page #f)
  #(ly:set-option 'tall-page-formats 'pdf)

  #(set-global-staff-size 16)

  \paper{
    line-width=7\in
    indent=0\mm
    left-margin = 0\mm
    right-margin = 0\mm

    oddFooterMarkup=##f
    oddHeaderMarkup=##f
    bookTitleMarkup=##f
    scoreTitleMarkup=##f
    ragged-right = ##f

    #(define fonts
      (set-global-fonts
       #:music "lilyjazz"
       #:brace "lilyjazz"
       %% #:roman "lilyjazz-text"
       #:sans "lilyjazz-chord"
       #:factor (/ staff-height pt 18)
     ))
  }

  \layout {
    \omit Staff.TimeSignature
    \context {
      \Score
      \override SpacingSpanner.uniform-stretching = ##t
    }
  }

  global = {
    \numericTimeSignature
    \time 4/4
    %% \tempo 4=224  % this would be over the clef on the first line

    %% See here for using colors
    %% http://lilypond.org/doc/v2.19/Documentation/notation/inside-the-staff#coloring-objects
    %% \override Score.RehearsalMark.color = #(x11-color "SlateBlue2")  % example using x11 colors
    \override Score.RehearsalMark.color = #darkred
    %% http://lilypond.org/doc/v2.19/Documentation/internals/rehearsalmark
    \override Score.RehearsalMark.font-size = 6

    \set Score.rehearsalMarkFormatter = #format-mark-box-alphabet
  }

#+end_src

* Assignment

Hey Bartev,

As per usual, awesome work on everything in your last assignment! Here are some ideas for your 27th assignment:

** Solo Transcription
Joe Henderson on Song for my Father - This is an iconic solo and record and one of my favorite things about this solo is Joe's use of motivic development and rhythm. He's so great at maintaining interest and developing ideas throughout his entire solo. Let's transcribe as much as we can on this and then try to ALSO solo over this tune in a similar manner.

[[https://www.youtube.com/watch?v=CWeXOm49kE0][Song For My Father (youtube)]]

** Technique
Now that we worked on the intervals in our major scales, let's do the same thing for melodic minor and harmonic minor. We can also alternate the direction, so for example, instead of playing C E D F E G and so forth, we can work these by playing the first interval ascending and the second descending: C E F D E G A F.... try working like this now to change things up as you get into melodic and harmonic minor.


** Tune
Let's learn the melody to Nica's Dream by Horace Silver and work on improvising through this tune in the original key.

** Composition
Let's compose 10 ii V lines that specifically use minor major 7 on the ii-7 and half whole diminished on the V7. Feel free to resolve these to major OR minor resolution chords!

* Technique
Melodic (\flat3) and harmonic (\flat3, \flat6) minor scales
* Variations on chord changes

** Major ii-V-I
#+begin_src lilypond :file major_ii_v_i.pdf
  \score {
    \new StaffGroup <<
      \new Lyrics \lyricmode {
        \markup \rN { ii -7 }1
        \markup \rN { V 7 }1
        \markup \rN { I }1
        \markup \rN { I }1
      }
      \new ChordNames { \chordmode { d:m7 g:7 c:maj7 c:maj7 }}
      \new Staff {
        \global
        \key c \major
        \relative c' {
          d4 f a c
          g4 b d f
          c4 e g b
          s1
        }
      }
    >>
  }
#+end_src

* Understanding the chords in Nica’s Dream

** A section

BV: m12 there’s a D7#9#5 into G7#5

2 chords with almost no notes in common.

What is this progression, and what do you play over these chords?


dom7\sharp5 is just another way to say dom7alt or dom7\sharp9 (dominant diminished).

So, your options:

D7\sharp5\sharp9
- D altered (Eb melodic minor)
- D H/W diminished (D, E\flat,  F, F\sharp,  G\sharp,  A, B, C)

G7\sharp5
- G altered (A\flat   melodic minor)
- G H/W diminished (G, A, B\flat, C, C\sharp, D\sharp, E, F\sharp)

** B section

dom7sus is the same as mixolydian but with more emphasis on the 4th, rather than the third! A nice shortcut you could also use is major pentatonic from the b7. So,

B\flat 7sus
- Bb mixolydian
- Ab major pentatonic

BV: I see the G half dim and I want to think minor ii-V, but the V has a #5, and it’s resolving to a dominant, not minor

You are indeed to think of that as a minor ii-V! The C7#5 is the same thing as a C7b13. It's sort of an "incomplete" chord, offering you the freedom to chose C7b9b13, C7alt, or C7#5#9 (dominant diminished). All of the options will sound great. Just pick your most comfortable for now and stick with that one!

BV: Then the F#-7 B7 goes into a Bb7sus. What is this?

B7 to Bb7sus is a tritone substitution approach! F7 to Bb7 is what it's swapping with.
