#+TITLE: Sax Lesson 27
#+AUTHOR: Bartev
#+OPTIONS: num:t toc:t

#+LATEX_HEADER: \usepackage[cm]{fullpage}
#+LATEX_HEADER: \usepackage[headheight=15pt, headsep=10pt, top=1in, bottom=1in, left=0.75in, right=0.75in]{geometry} % Ensure sufficient header space
#+BIND: org-latex-image-default-width ".98\\linewidth"

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhf{}
#+LATEX_HEADER: \fancyhead[L]{\textbf{LJV Lesson 27}} % Left header with title
#+LATEX_HEADER: \fancyhead[R]{\textbf{Bartev - Lesson 27 (2025-03)}} % Right header with author
#+LATEX_HEADER: \fancyfoot[C]{\thepage}
#+LATEX_HEADER: \fancyfoot[R]{Printed \today} % Right footer with today's date
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0.4pt} % Optional: Add a horizontal rule below the header

#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \let\ps@plain\ps@fancy % Apply "fancy" style to the first page
#+LATEX_HEADER: \let\maketitle\relax % Suppress default title/author rendering
#+LATEX_HEADER: \makeatother

#+PROPERTY: header-args:lilypond :noweb yes :exports results
#+PROPERTY: header-args:lilypond :prologue (org-babel-ref-resolve "settings[]")

#+name: settings
#+begin_src lilypond :exports none
  \version "2.24.2"

  \include "lilypond-book-preamble.ly"

  \include "jazzchords.ily"
  %% \include "lilyjazz.ily"
  \include "jazzextras.ily"
  \include "roman_numeral_analysis_tool.ily"
  \include "bv_definitions.ily"

  #(ly:set-option 'use-paper-size-for-page #f)
  #(ly:set-option 'tall-page-formats 'pdf)

  #(set-global-staff-size 16)

  \paper{
    line-width=7\in
    indent=0\mm
    left-margin = 0\mm
    right-margin = 0\mm

    oddFooterMarkup=##f
    oddHeaderMarkup=##f
    bookTitleMarkup=##f
    scoreTitleMarkup=##f
    ragged-right = ##f

    #(define fonts
      (set-global-fonts
       #:music "lilyjazz"
       #:brace "lilyjazz"
       ; #:roman "lilyjazz-text"
       #:sans "lilyjazz-chord"
       #:factor (/ staff-height pt 18)
     ))
  }

  \layout {
    \omit Staff.TimeSignature
    \context {
      \Score
      \override SpacingSpanner.uniform-stretching = ##t
    }
  }

  global = {
    \numericTimeSignature
    \time 4/4
    %% \tempo 4=224  % this would be over the clef on the first line

    %% See here for using colors
    %% http://lilypond.org/doc/v2.19/Documentation/notation/inside-the-staff#coloring-objects
    %% \override Score.RehearsalMark.color = #(x11-color "SlateBlue2")  % example using x11 colors
    \override Score.RehearsalMark.color = #darkred
    %% http://lilypond.org/doc/v2.19/Documentation/internals/rehearsalmark
    \override Score.RehearsalMark.font-size = 6

    \set Score.rehearsalMarkFormatter = #format-mark-box-alphabet
  }

#+end_src

* Assignment :noexport:

Hey Bartev,

As per usual, awesome work on everything in your last assignment! Here are some ideas for your 27th assignment:

** Solo Transcription
Joe Henderson on Song for my Father - This is an iconic solo and record and one of my favorite things about this solo is Joe's use of motivic development and rhythm. He's so great at maintaining interest and developing ideas throughout his entire solo. Let's transcribe as much as we can on this and then try to ALSO solo over this tune in a similar manner.

[[https://www.youtube.com/watch?v=CWeXOm49kE0][Song For My Father (youtube)]]

** Technique
Now that we worked on the intervals in our major scales, let's do the same thing for melodic minor and harmonic minor. We can also alternate the direction, so for example, instead of playing C E D F E G and so forth, we can work these by playing the first interval ascending and the second descending: C E F D E G A F.... try working like this now to change things up as you get into melodic and harmonic minor.


** Tune
Let's learn the melody to Nica's Dream by Horace Silver and work on improvising through this tune in the original key.

** Composition
Let's compose 10 ii V lines that specifically use minor major 7 on the ii-7 and half whole diminished on the V7. Feel free to resolve these to major OR minor resolution chords!

* Technique :noexport:
Melodic (\flat3) and harmonic (\flat3, \flat6) minor scales
* Variations on chord changes  :noexport:
** ii-V-I with minMaj7 -- H/W dim --> Maj7

#+begin_src lilypond :file scales-min-maj-to-maj7.pdf
  \score {
    \new StaffGroup <<
      \new Lyrics \lyricmode {
        \markup \rN { ii-M7 }1
        \markup \rN { V 7 }1
        \markup \rN { I }1
        %% \markup \rN { I }1
      }
      \new ChordNames { \chordmode
                        { d1:maj7.3-
                          g4:7 g8:7.9+ g8:7.9- g4:13- g4:m7.5-
                          c1:maj7
                          d4:maj7.3- }}
      \new Staff {
        \global
        \key c \major
        \relative c' {
          d8_\markup {"Melodic minor"} e f g a b cis d
          g,8_\markup "Half/Whole Diminished" aes bes b des d e f 
          c,8_\markup "Major (Ionian)" d e f g a b c
          << d,1 f! a cis >>
                  }
      }
    >>
  }
#+end_src

** ii-V-I with minMaj7 -- H/W dim --> min7
#+begin_src lilypond :file scales-min-maj-to-min7.pdf
  \score {
    \new StaffGroup <<
      \new Lyrics \lyricmode {
        \markup \rN { ii-M7 }1
        \markup \rN { V 7 }1
        \markup \rN { i-7 }1
        \markup \rN { i-7 }1
      }
      \new ChordNames { \chordmode
                        { d1:maj7.3-
                          g4:7 g8:7.9+ g8:7.9- g4:13- g4:m7.5-
                          c1:m7
                          g2:7.9+ g4:7.9- g4:m7.5-}}
      \new Staff {
        \global
        \key c \major
        \relative c' {
          d8_\markup {"Melodic minor"} e f g a b cis d
          g,8_\markup "Half/Whole Diminished" aes bes b des d e f 
          c,8_\markup "Dorian minor" d ees f g a bes c
          << g2 b d f! bes >>
          << g,4 b d f! aes>>
          << g,4 bes des f!>>
        }
      }
    >>
  }
#+end_src


** Major ii-V-I
#+begin_src lilypond :file major_ii_v_i.pdf
  \score {
    \new StaffGroup <<
      \new Lyrics \lyricmode {
        \markup \rN { ii -7 }1
        \markup \rN { V 7 }1
        \markup \rN { I }1
        \markup \rN { I }1
      }
      \new ChordNames { \chordmode { d:m7 g:7 c:maj7 c:maj7 }}
      \new Staff {
        \global
        \key c \major
        \relative c' {
          d4 f a c
          g4 b d f
          c4 e g b
          s1
        }
      }
    >>
  }
#+end_src



* Understanding the chords in Nica’s Dream  :noexport:

** A section

BV: m12 there’s a D7#9#5 into G7#5

2 chords with almost no notes in common.

What is this progression, and what do you play over these chords?


dom7\sharp5 is just another way to say dom7alt or dom7\sharp9 (dominant diminished).

So, your options:

D7\sharp5\sharp9
- D altered (Eb melodic minor)
- D H/W diminished (D, E\flat,  F, F\sharp,  G\sharp,  A, B, C)

G7\sharp5
- G altered (A\flat   melodic minor)
- G H/W diminished (G, A, B\flat, C, C\sharp, D\sharp, E, F\sharp)
  
** B section

dom7sus is the same as mixolydian but with more emphasis on the 4th, rather than the third! A nice shortcut you could also use is major pentatonic from the b7. So,

B\flat 7sus
- Bb mixolydian
- Ab major pentatonic

BV: I see the G half dim and I want to think minor ii-V, but the V has a #5, and it’s resolving to a dominant, not minor

You are indeed to think of that as a minor ii-V! The C7#5 is the same thing as a C7b13. It's sort of an "incomplete" chord, offering you the freedom to chose C7b9b13, C7alt, or C7#5#9 (dominant diminished). All of the options will sound great. Just pick your most comfortable for now and stick with that one!

BV: Then the F#-7 B7 goes into a Bb7sus. What is this?

B7 to Bb7sus is a tritone substitution approach! F7 to Bb7 is what it's swapping with.

* Composition

** C-7 (1) ii-V-I with minMaj7 -- H/W dim --> min7
#+begin_src lilypond :file c_min_1.pdf
  \score {
    \new StaffGroup <<
      \new Lyrics \lyricmode {
        \markup \rN { ii-M7 }1
        \markup \rN { V 7 s9}1
        \markup \rN { i-7 }1
        \markup \rN { i-7 }1
      }
      \new ChordNames { \chordmode
                        { d1:maj7.3-
                          g1:7.9+
                          c1:m7
                          c1:m7}}
      \new Staff {
        \global
        \key c \major
        \relative c'' {
          a8 a f g a f~ f4
          g8 g e f g e~ e4
          r8 d( ees) f( g) a( bes) c
          r8 d~ d4 r2
        }
      }
    >>
  }
#+end_src


** D-7 ii-V-I with minMaj7 -- H/W dim --> min7
#+begin_src lilypond :file d_min_1.pdf
  romans = \lyricmode {
        \markup \rN { ii-M7 }1
        \markup \rN { V 7 s9}1
        \markup \rN { i-7 }1
        \markup \rN { i-7 }1
      }
  chordChanges = \chordmode { e1:maj7.3-
                              a1:7.9+
                              d1:m7
                              d1:m7}
  \score {
    \new StaffGroup <<

      \new Lyrics \repeat unfold 1 { \romans }
      \new ChordNames { \repeat unfold 1 { \chordChanges } }
      
      \new Staff {
        \global
        \key c \major
        \relative c'' {
          r4 r4 r8 b \tuplet 3/2 { cis8 dis e }
          g8 e cis bes a c ees ges
          a8 f e g f d~ d4
          r1
          \break
        }
      }
    >>
  }
#+end_src

** D-7 ii-V-I with minMaj7 -- H/W dim --> min7
#+begin_src lilypond :file d_min_2.pdf
  romans = \lyricmode {
        \markup \rN { ii-M7 }1
        \markup \rN { V 7 s9}1
        \markup \rN { i-7 }1
        \markup \rN { i-7 }1
      }
  chordChanges = \chordmode { e1:maj7.3-
                              a1:7.9+
                              d1:m7
                              d1:m7}
  \score {
    \new StaffGroup <<

      \new Lyrics \repeat unfold 1 { \romans }
      \new ChordNames { \repeat unfold 2 { \chordChanges } }
      
      \new Staff {
        \global
        \key c \major
        \relative c'' {
          b8 a g e~ e4 r
          bes'8 a g ees~ ees4 r
          a8 g f d~ d4 r
          r1
          \break

          b'8 c b a g e~ e4
          bes'8 c bes a g ees~ ees4
          a8 bes a g f c f d~
          d4 r r2        
        }
      }
    >>
  }
#+end_src
** D-7 ii-V-I with minMaj7 -- H/W dim --> min7
#+begin_src lilypond :file d_min_3.pdf
  romans = \lyricmode {
        \markup \rN { ii-M7 }1
        \markup \rN { V 7 s9}1
        \markup \rN { i-7 }1
        \markup \rN { i-7 }1
      }
  chordChanges = \chordmode { e1:maj7.3-
                              a1:7.9+
                              d1:m7
                              d1:m7}
  \score {
    \new StaffGroup <<
      
      \new Lyrics \repeat unfold 1 { \romans }
      \new ChordNames {\repeat unfold 1 { \chordChanges } }
      
      \new Staff {
        \global
        \key c \major
        \relative c'' {
          r8 cis \tuplet 3/2 { dis8 e g } b4 a
          \tuplet 3/2 { d4 cis bes~ } bes4 r8 g
          a8 f d g e c f d
          b8 e c a d f r4
          \break
        }
      }
    >>
  }
#+end_src

** D-7 ii-V-I with minMaj7 -- H/W dim --> min7
#+begin_src lilypond :file d_min_4.pdf
  romans = \lyricmode {
    \markup \rN { ii-M7 }1
    \markup \rN { V 7 s9}1
    \markup \rN { i-7 }1
    \markup \rN { i-7 }1
  }
  chordChanges = \chordmode { e1:maj7.3-
                              a1:7.9+
                              d1:m7
                              d1:m7}
  \score {
    \new StaffGroup <<

      \new Lyrics \repeat unfold 1 { \romans }
      \new ChordNames {\repeat unfold 1 { \chordChanges }}
      
      \new Staff {
        \global
        \key c \major
        \relative c''' {
          r8 g fis f e4-. r
          r8 c' b bes a4-. r
          r8 fis f e d4-. r
          r1
        }
      }
    >>
  }
#+end_src

#+RESULTS:
[[file:d_min_4.pdf]]

** C-7 ii-V-I with minMaj7 -- H/W dim --> min7
Type some stuff here

#+begin_src lilypond :file c_min_2.pdf
  romans = \lyricmode {
    \markup \rN { ii-M7 }1
    \markup \rN { V 7 s9}1
    \markup \rN { i-7 }1
    \markup \rN { i-7 }1
  }
  chordChanges = \chordmode { d1:maj7.3-
                              g1:7.9+
                              c1:m7
                              c1:m7}
  \score {
    \new StaffGroup <<

      \new Lyrics \repeat unfold 1 { \romans }
      \new ChordNames {\repeat unfold 1 { \chordChanges }}
      
      \new Staff {
        \global
        \key c \major
        \relative c''' {
          g8 ees f g aes b cis r
          r8 c b bes aes g f g
          r8 c ees d c bes g f
          g4 bes8 c r2
        }
      }
    >>
  }
#+end_src

** D-7 ii-V-I with minMaj7 -- H/W dim --> min7
#+begin_src lilypond :file d_min_5.pdf
  romans = \lyricmode {
    \markup \rN { ii-M7 }1
    \markup \rN { V 7 s9}1
    \markup \rN { i-7 }1
    \markup \rN { i-7 }1
  }
  chordChanges = \chordmode { e1:maj7.3-
                              a1:7.9+
                              d1:m7
                              d1:m7}
  \score {
    \new StaffGroup <<

      \new Lyrics \repeat unfold 1 { \romans }
      \new ChordNames {\repeat unfold 1 { \chordChanges }}
      
      \new Staff {
        \global
        \key c \major
        \relative c'' {
          r8 e dis e  g e g b~
          b8 g bes cis  g e cis bes
          c8 f e d  c a c f
          r1
        }
      }
    >>
  }
#+end_src

